defaults:
  - override /database@_global_: island_small
  - override /evolution@_global_: small_budget
  - override /task@_global_: nikkei_shock
  - override /cluster@_global_: local
  - _self_

evaluate_function:
  llm_analyst:
    model_names: "gpt-4.1"
    temperatures: 0.0
    max_tokens: 8196
    reasoning_efforts: "low"
    verbose: true
  llm_reviewer:
    model_names: "gpt-4.1"
    temperatures: 0.0
    max_tokens: 8196
    reasoning_efforts: "low"
    verbose: true

evo_config:
  num_generations: 10
  llm_models:
    - "gpt-4.1-mini"

variant_suffix: "_example"
