defaults:
  - override /database@_global_: island_small
  - override /evolution@_global_: zero_budget
  - override /task@_global_: nikkei_shock
  - override /cluster@_global_: local
  - _self_

evaluate_function:
  llm_analyst:
    model_names: "ollama::llama3.1:8b"
    temperatures: 0.0
    max_tokens: 8196
    reasoning_efforts: "low"
    verbose: true
  llm_reviewer:
    model_names: "ollama::llama3.1:8b"
    temperatures: 0.0
    max_tokens: 8196
    reasoning_efforts: "low"
    verbose: true

variant_suffix: "_example_free"
